try {
  const m = 1;
  const n = m + z;
  console.log(n);
} catch (error) {
  console.log(error.name);
}
